// Babel's Error Format
// Copyright (C) 2015 The Babel Authors

package babel

// *** AUTO-GENERATED FILE - DO NOT MODIFY ***
// *** Generated from /Users/michael/gocode/etc/babeltemplates/error.babel ***

import (
	"time"
)




// Error defines a single error message and code that might be localized
// and displayed to a caller.
type Error struct {
	// The service-specific error code
	Code *string `json:"Code,omitempty"`

	// The text of the error in US-English
	Message *string `json:"Message,omitempty"`

	// The list of parameters to the error message. This could be used by
	// localization systems to generate messages based on the error code.
	Params []*string `json:"Params,omitempty"`

}

// Init sets default values for a Error
func (obj *Error) Init() *Error {
	obj.Params = make([]*string, 0)
	return obj
}

// ServiceError defines the error response generated by Babel for service failures
type ServiceError struct {
	// Time of the error
	Time *time.Time `json:"Time,omitempty"`

	// Tags to categorize the error
	Tags []*string `json:"Tags,omitempty"`

	// A list of errors that occurred
	Errors []*Error `json:"Errors,omitempty"`

	// Context is a map of additional error details and context
	Context map[string]map[string]*string `json:"Context,omitempty"`

	// Details contains optional detailed error information, such as error messages
	// or a stack trace specific to the given server environment
	Details *string `json:"Details,omitempty"`

	// Inner points to a service error propagated from another tier that is using Babel
	Inner *ServiceError `json:"Inner,omitempty"`

}

// Init sets default values for a ServiceError
func (obj *ServiceError) Init() *ServiceError {
	obj.Tags = make([]*string, 0)
	obj.Errors = make([]*Error, 0)
	obj.Context = make(map[string]map[string]*string, 0)
	return obj
}
